"""Transformer module for executing tasks and transforming data state.

This module provides the core transformation engine that executes tasks
generated by Splitters and produces new data states.

Architecture Principles:
    - Transformers execute tasks, don't create them
    - Always copy data state before modifying
    - Update task status and results
    - Handle errors gracefully
    - Pass context to processors

Exports:
    - Transformer: Abstract base class
    - BaseTransformer: Basic implementation
    - BatchTransformer: Batch-optimized implementation (optional)
"""

from .transformer import Transformer
from .base_transformer import BaseTransformer

__all__ = [
    'Transformer',
    'BaseTransformer',
]
