# Database Configuration
# 生产环境配置使用环境变量，敏感信息存储在.env文件中

database:
  # 主数据库配置
  mysql:
    host: ${MYSQL_HOST:-rm-bp13t8tx0697ewx4wpo.mysql.rds.aliyuncs.com}
    port: ${MYSQL_PORT:-3306}
    user: ${MYSQL_USER:-chenyang}
    password: ${MYSQL_PASSWORD}  # 从环境变量读取
    database: ${MYSQL_DATABASE:-ai_terminal}
    charset: ${MYSQL_CHARSET:-utf8mb4}

    # 连接池配置
    pool:
      min_size: ${MYSQL_POOL_MIN:-1}
      max_size: ${MYSQL_POOL_MAX:-10}
      echo: ${MYSQL_ECHO:-false}
      autocommit: false

    # 连接选项
    options:
      connect_timeout: 10
      read_timeout: 30
      write_timeout: 30

  # 持久化配置
  persistence:
    # 任务持久化
    task_persister:
      enabled: true
      interval: 30  # 秒
      batch_size: 100

    # 检查点配置
    checkpoint:
      enabled: true
      interval: 60  # 秒
      directory: ./checkpoints
      compression: true
      max_age_days: 7

    # 日志持久化
    log_persister:
      enabled: true
      batch_size: 50
      flush_interval: 10  # 秒

  # 表名配置
  tables:
    sessions: translation_sessions
    tasks: translation_tasks
    checkpoints: translation_checkpoints
    logs: translation_logs
    metrics: translation_metrics