# Processors configuration for task execution
#
# Each processor defines how to transform tasks into results

processors:
  # LLM-based translation processors
  llm_qwen:
    name: "通义千问翻译"
    class: services.llm.qwen_provider.QwenProvider
    description: "使用阿里云通义千问进行智能翻译"
    type: llm_translation
    config:
      model: qwen-plus
      temperature: 0.3
    enabled: true
    requires_llm: true
    parameters:
      maxWorkers:
        type: number
        label: "最大并发数"
        default: 10
        min: 1
        max: 50

  llm_openai:
    name: "OpenAI GPT翻译"
    class: services.llm.openai_provider.OpenAIProvider
    description: "使用OpenAI GPT模型进行翻译"
    type: llm_translation
    config:
      model: gpt-4
      temperature: 0.3
    enabled: true
    requires_llm: true
    parameters:
      maxWorkers:
        type: number
        label: "最大并发数"
        default: 10
        min: 1
        max: 50

  # Simple transformation processors
  uppercase:
    name: "大写转换"
    class: services.processors.uppercase_processor.UppercaseProcessor
    description: "将文本转换为大写形式"
    type: text_transform
    config: {}
    enabled: true
    requires_llm: false
    parameters:
      maxWorkers:
        type: number
        label: "最大并发数"
        default: 20
        min: 1
        max: 100

  lowercase:
    name: "小写转换"
    class: services.processors.lowercase_processor.LowercaseProcessor
    description: "将文本转换为小写形式"
    type: text_transform
    config: {}
    enabled: true
    requires_llm: false
    parameters: {}

  trim:
    name: "文本修剪"
    class: services.processors.trim_processor.TrimProcessor
    description: "去除空格并限制文本长度"
    type: text_transform
    config:
      max_length: 100
      strip: true
    enabled: false
    requires_llm: false
    parameters: {}

  # Validation processors
  validate:
    name: "质量验证"
    class: services.processors.validate_processor.ValidateProcessor
    description: "验证翻译结果质量"
    type: validation
    config:
      rules:
        - no_empty
        - no_special_chars
        - length_check
    enabled: false
    requires_llm: false
    parameters: {}

# Processor sets for common scenarios
processor_sets:
  # Default LLM translation
  default_translation:
    processor: llm_qwen
    max_workers: 10
    retry_count: 3

  # CAPS transformation
  caps_transform:
    processor: uppercase
    max_workers: 20  # Simple operation, can use more workers
    retry_count: 1

# Default processor
default_processor: llm_qwen
